{{- if eq .Values.rbac.enable true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{  include "chart.fullname" . }}-sakey
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  {{- if .Values.docker.b64encodedDockerConfig }}
  .dockerconfigjson: {{ .Values.docker.b64encodedDockerConfig }}
  {{ else }}
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.docker.registry (printf "%s:%s" .Values.docker.username .Values.docker.password | b64enc) | b64enc }}
  {{- end }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "chart.fullname" . }}-serviceaccount
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
- name: {{  include "chart.fullname" . }}-sakey
{{ end }}
